pipeline:
  verify:
    image: python:3.4.9-alpine
    commands:
      - python setup.py verify
    when:
      event: [ tag ]
  
  plugin:
    image: gjtempleton/drone-pypi
    repository: https://gumgum.jfrog.io/gumgum/api/pypi/pypi-local
    secrets: [ username, password ]
    when:
      event: [ tag ]

  notify_slack:
    image: plugins/slack
    channel: cv-drone
    username: dronebot
    icon_emoji: shipitparrot
    secrets:
      - source: slack_webhook_url
        target: slack_webhook
    template: >
      {{#success build.status}}
        CV Base Images build {{build.number}} for {{build.branch}} succeeded! :tot:
      {{else}}
        CV Base Images build {{build.number}} for {{build.branch}} failed :ohno:
      {{/success}}
        Commit message: ${DRONE_COMMIT_MESSAGE}
        {{build.link}}
    when:
      status: [ success, failure ]
      event: [ tag ]
