stages:
  - deploy

deploying:artifactory:
  image: python:3.6
  stage: deploy
  before_script:
    - pip install twine
  variables:
    TWINE_USERNAME: $ARTIFACTORY_USERNAME
    TWINE_PASSWORD: $ARTIFACTORY_PASSWORD
    TWINE_REPOSITORY_URL: https://$ARTIFACTORY_PYPI
  script:
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags

# deploying_to_pypi:
#   image: python:3.6
#   stage: deploy
#   before_script:
#     - pip install twine
#   variables:
#     TWINE_USERNAME: $TWINE_USERNAME
#     TWINE_PASSWORD: $TWINE_PASSWORD
#   script:
#     - python setup.py sdist
#     - twine upload dist/*
#   only:
#     - tags

pages:
  stage: deploy
  image: python:3.6
  before_script:
    - pip install sphinx sphinx-rtd-theme sphinx-pypi-upload
  script:
    - python setup.py build_sphinx
    - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
    - master
