language: python
python:
- '3.6'
script:
- touch test_runner_placeholder
deploy:
  provider: pypi
  script: python3 setup.py verify
  on:
    tags: true
    repo: gumgum/multivitamin
    branch: master
    distributions: sdist bdist_wheel
  user: mgreenberg1
  password:
    secure: hKYYw3H1gvR7PwDbL04U4kC2KoGfM7xPhagrSAYqbwoCURMv9L7gn2P1ZqUo5qpjnQYK16+gZJ5I01tfaIaixgTzDbsEdykQLtD4IflXeuS+NtotNBUAwNN4j4C7JWhmapoF7iELYhUlfrW+JdI8nHuJCBYZXfcxNi8uE9DdcE4SC36PNCYq9zR+na9W+ZFJyqP1I9C2BtQbJStdvzC7iPlBVGUIbCtDB3q+jIeX+VeVefw7WuLxOc/J/yQlPAHF5/VLDzGP/oLV90WUkvOFko54WppRf4CW+i26pCWJCoLpWe2Y9+qZjuxNDeaLBEMzpkTe8/L0XePqgXsxcEDFaP5L05MJ49XOvFb/O6CxKFnIaLR9/wucuMLDiu8OgBo0abq/9hKFreoKDRCPrgfiTyvDnMY0HcPjFMur2y4LEzpYflXsBsiaYEyNG+pFoEptig0EKh2IvEOjXIKkJEHRh3AAKZDYDuHYkSPxRmkt9JTZLztzNZ+uaTTHiAmlsxWNs4Yr5PhJ5Sw9/Z1Dz5SiPJI9BTs//ag+XrgEH8iRaqpvjCXR3iZ9sFp/HTZUfPSV47G/jvTOIcG6MdjREueUnFneVqcznOUIiZlkopzc0zUyMc54vrYugLi6mqj1WNLVy7ENvfQIDyqYj8HUT0y4pvxdOxCFHSmIcCksoUoECG8=
